fixed parsing error; support multiple ADXL362 devices on different CE…
szecke01/ADXL362-RPi pull request #1
Opened 2017-03-05 15:26 UTC by Human

… pins

2017-03-09 17:57 UTC, natetarrh requested changes
thanks for the fixes!

2017-03-09 17:57 UTC, natetarrh commented on ADXL362.py
> +       return val
let's keep the indent at 4 spaces and fix the docstring indent instead

2017-03-10 15:23 UTC, Human commented on ADXL362.py
> +       return val
Cool. I'll submit new PRs, since I just bundled a few of them together in the same branch.

2017-03-10 15:24 UTC, Human commented
Closing this PR to spawn 3 new ones.

2017-03-10 15:24 UTC, closed without merging